# Generated by Django 3.0.5 on 2020-04-08 00:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('agroia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_upload',
            field=models.DateField(default=datetime.datetime(2020, 4, 8, 0, 51, 28, 141623, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='item',
            name='country',
            field=models.CharField(max_length=100),
        ),
    ]
