# Generated by Django 3.0.3 on 2020-06-10 02:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agroia', '0006_auto_20200605_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='imagen',
            field=models.ImageField(null=True, upload_to='crops'),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_upload',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
