# Generated by Django 3.0.3 on 2020-06-10 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agroia', '0007_auto_20200609_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='country',
        ),
        migrations.AddField(
            model_name='item',
            name='upload_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
