# Generated by Django 3.0.3 on 2020-06-10 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agroia', '0008_auto_20200609_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='imagen',
            new_name='image',
        ),
    ]
