# Generated by Django 3.0.3 on 2020-06-12 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agroia', '0012_auto_20200611_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agroia.Method'),
        ),
    ]
