# Generated by Django 3.0.3 on 2020-06-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroia', '0013_item_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='method',
            old_name='script',
            new_name='zip',
        ),
        migrations.RemoveField(
            model_name='method',
            name='weights',
        ),
        migrations.AddField(
            model_name='method',
            name='command',
            field=models.CharField(default='python', max_length=500),
        ),
    ]
