# Generated by Django 3.0.3 on 2020-06-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroia', '0014_auto_20200614_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
