# Generated by Django 3.0.3 on 2020-06-14 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agroia', '0015_auto_20200614_0157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='method',
            old_name='zip',
            new_name='file',
        ),
    ]
